Obtain commits from the master

diff --git a/scala-days-2018/scalac-native/scalac-native b/scala-days-2018/scalac-native/scalac-native
--- a/scala-days-2018/scalac-native/scalac-native
+++ b/scala-days-2018/scalac-native/scalac-native
@@ -1,1 +1,15 @@
-./scalac -classpath '""' -Dscala.boot.class.path=$SCALA_HOME/lib/jline.jar:$SCALA_HOME/lib/repl.jar:$SCALA_HOME/lib/scala-compiler-doc.jar:$SCALA_HOME/lib/scala-compiler-interactive.jar:$SCALA_HOME/lib/scala-compiler.jar:$SCALA_HOME/lib/scala-library.jar:$SCALA_HOME/lib/scala-parser-combinators_2.12.0-M2-1.0.4.jar:$SCALA_HOME/lib/scala-partest-extras.jar:$SCALA_HOME/lib/scala-partest-javaagent.jar:$SCALA_HOME/lib/scala-reflect.jar:$SCALA_HOME/lib/scala-repl-frontend.jar:$SCALA_HOME/lib/scala-repl-jline-embedded.jar:$SCALA_HOME/lib/scala-repl-jline.jar:$SCALA_HOME/lib/scala-swing_2.12.0-M2-2.0.0-M2.jar:$SCALA_HOME/lib/scala-xml_2.12.0-M2-1.0.5.jar:$SCALA_HOME/lib/scalap.jar:$GRAALVM_HOME/jre/lib/rt.jar -Dscala.home=$SCALA_HOME -Dscala.usejavacp=true -Denv.emacs= $@
+#!/bin/sh
+
+[ -z "$GRAALVM_HOME" ] && echo "GRAALVM_HOME is currently not set. This script will not work." && exit 1
+[ ! -f "$GRAALVM_HOME/bin/native-image" ] && echo "Can't find native-image in $GRAALVM_HOME. Check that the directory is valid." && exit 1
+[ -z "$SCALA_HOME" ] && echo "SCALA_HOME is currently not set. This script will not work." && exit 1
+SCALA_LIB="$SCALA_HOME/lib"
+if [ -d "$SCALA_HOME/libexec" ]; then
+   SCALA_LIB="$SCALA_HOME/libexec/lib"
+fi
+[ ! -d "$SCALA_LIB" ] && echo "Can't find jars in $SCALA_LIB. Check that the Scala instalation is correct." && exit 1
+for filename in $SCALA_LIB/*.jar; do
+    SCALA_LIB_CLASSPATH=$filename:$SCALA_LIB_CLASSPATH
+done
+
+./scalac -classpath '""' -Dscala.boot.class.path=$SCALA_LIB_CLASSPATH:$GRAALVM_HOME/jre/lib/rt.jar -Dscala.home=$SCALA_HOME -Dscala.usejavacp=true -Denv.emacs= $@
