Test and update scala-examples

diff --git a/scala-examples/scalac-native/scalac-native b/scala-examples/scalac-native/scalac-native
--- a/scala-examples/scalac-native/scalac-native
+++ b/scala-examples/scalac-native/scalac-native
@@ -1,7 +1,7 @@
 #!/bin/sh
 
-[ -z "$GRAALVM_HOME" ] && echo "GRAALVM_HOME is currently not set. This script will not work." && exit 1
-[ ! -f "$GRAALVM_HOME/bin/native-image" ] && echo "Can't find native-image in $GRAALVM_HOME. Check that the directory is valid." && exit 1
+[ -z "$JAVA_HOME" ] && echo "JAVA_HOME is currently not set. This script will not work." && exit 1
+[ ! -f "$JAVA_HOME/bin/native-image" ] && echo "Can't find native-image in $JAVA_HOME. Check that the directory is valid." && exit 1
 [ -z "$SCALA_HOME" ] && echo "SCALA_HOME is currently not set. This script will not work." && exit 1
 SCALA_LIB="$SCALA_HOME/lib"
 if [ -d "$SCALA_HOME/libexec" ]; then
